groups:

  - name: server-alerts

    rules:

      # =====================================================
      # HIGH CPU
      # =====================================================

      - alert: HighCPU

        expr: |
          100 - (
            avg by(instance) (
              rate(node_cpu_seconds_total{mode="idle"}[1m])
            ) * 100
          ) > 50

        for: 30s

        labels:

          severity: critical

        annotations:

          summary: "High CPU detected"

          description: >
            CPU usage on {{ $labels.instance }}
            has been above 50% for more than 30 seconds.


      # =====================================================
      # HIGH MEMORY
      # =====================================================

      - alert: HighMemory

        expr: |
          (
            1 -
            (
              node_memory_MemAvailable_bytes
              /
              node_memory_MemTotal_bytes
            )
          ) * 100 > 90

        for: 30s

        labels:

          severity: critical

        annotations:

          summary: "High memory usage detected"

          description: >
            Memory usage on {{ $labels.instance }}
            has been above 90% for more than 30 seconds.


      # =====================================================
      # HIGH DISK
      # =====================================================

      - alert: HighDiskUsage

        expr: |
          (
            1 -
            (
              node_filesystem_avail_bytes{
                mountpoint="/",
                fstype!~"tmpfs|overlay"
              }
              /
              node_filesystem_size_bytes{
                mountpoint="/",
                fstype!~"tmpfs|overlay"
              }
            )
          ) * 100 > 90

        for: 1m

        labels:

          severity: critical

        annotations:

          summary: "High disk usage detected"

          description: >
            Root filesystem usage on {{ $labels.instance }}
            has been above 90% for more than 1 minute.
